name: Build sdist and wheels and publish to PyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install ninja
      run: pipx install ninja

    - name: Install alsa deps
      run: sudo apt-get install libasound2-dev

    - name: Build sdist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check --strict dist/*

    - name: Upload sdist
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  build_win_wheels:
    name: Build wheels on Windows
    runs-on: windows-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels_win
        path: wheelhouse/*.whl

  build_macos_wheels:
    name: Build wheels on macOS
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23
      env:
        # Skip trying to test arm64 builds on Intel Macs
        CIBW_TEST_SKIP: "*-macosx_arm64 *-macosx_universal2:arm64"

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels_macos
        path: wheelhouse/*.whl

  build_linux_wheels:
    name: Build wheels on Linux
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23
      env:
        CIBW_BUILD: 'cp311-* cp312-* cp313-* pp39-* pp310-* pp311-*'
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_I686_IMAGE: manylinux2014

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels_linux
        path: wheelhouse/*.whl

  build_linux_legacy_wheels:
    name: Build legacy wheels on Linux
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23
      env:
        CIBW_BUILD: 'cp39-* cp310-*'
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010
        CIBW_MANYLINUX_I686_IMAGE: manylinux2010

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels_linux_legacy
        path: wheelhouse/*.whl

  build_linux_aarch64_wheels:
    name: Build wheels on Linux aarch64
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23
      env:
        CIBW_ARCHS: aarch64
        CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels_linux_aarch64
        path: wheelhouse/*.whl

  upload_pypi:
    needs: [build_linux_wheels, build_linux_aarch64_wheels, build_linux_legacy_wheels, build_win_wheels, build_macos_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: PyPI release
    steps:
    - uses: actions/upload-artifact/merge@v4

    - uses: actions/download-artifact@v3
      with:
        name: merged-artifacts
        path: dist

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.6
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verify-metadata: false
